// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SkillfactoryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testsHeaderselements() {
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    {
      WebElement element = driver.findElement(By.cssSelector(".t978__tm-link:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".t978__tm-link_active")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#nav623893182 .t978__menu-item:nth-child(1) .t978__link-inner"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("#nav623893182 .t978__menu-item:nth-child(1) .t978__link-inner")).click();
    vars.put("win1683", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win1683").toString());
    driver.findElement(By.cssSelector(".internal-link > .tn-atom__img")).click();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
    driver.switchTo().window(vars.get("win1683").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("БЕСПЛАТНО")).click();
    vars.put("win7328", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7328").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".internal-link > .tn-atom__img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.switchTo().window(vars.get("win1683").toString());
    driver.close();
    driver.switchTo().window(vars.get("win7328").toString());
    driver.findElement(By.cssSelector(".parpadding rect:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".internal-link > .tn-atom__img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".internal-link > .tn-atom__img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(3) > .main__nav-item")).click();
    vars.put("win7819", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7819").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__4693509551679923694091 .tn-atom__img")).click();
    vars.put("win435", waitForWindow(2000));
    driver.switchTo().window(vars.get("win435").toString());
    driver.switchTo().window(vars.get("win7819").toString());
    driver.close();
    driver.switchTo().window(vars.get("win435").toString());
    driver.switchTo().window(vars.get("win7328").toString());
    driver.close();
    driver.switchTo().window(vars.get("win435").toString());
    {
      WebElement element = driver.findElement(By.cssSelector("li:nth-child(4) > .main__nav-item"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(4) > .main__nav-item")).click();
    vars.put("win593", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win593").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".internal-link > .tn-atom__img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".internal-link > .tn-atom__img")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win435").toString());
    driver.close();
    driver.switchTo().window(vars.get("win593").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(5) > .main__nav-item")).click();
    vars.put("win5258", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5258").toString());
    js.executeScript("window.scrollTo(0,3100)");
    driver.switchTo().frame(3);
    driver.findElement(By.cssSelector(".close-icon")).click();
    driver.switchTo().defaultContent();
    driver.switchTo().frame(5);
    driver.findElement(By.cssSelector(".close-icon")).click();
    driver.close();
    driver.switchTo().window(vars.get("win593").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector("li:nth-child(6) > .main__nav-item")).click();
    vars.put("win4843", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4843").toString());
    driver.findElement(By.cssSelector(".t228__imglogo")).click();
    driver.switchTo().window(vars.get("win593").toString());
    driver.close();
    driver.switchTo().window(vars.get("win4843").toString());
  }
  @Test
  public void testTextBox() {
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("andrei_telkov@mail.ru");
    driver.findElement(By.name("tildaspec-phone-part[]")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).sendKeys("(999) 999-99-99");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Andrey");
    driver.findElement(By.cssSelector("#rec625407935 .t396__artboard")).click();
    driver.findElement(By.name("email")).sendKeys(" ");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("andrei_telkov@mail.ru");
    driver.findElement(By.name("tildaspec-phone-part[]")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).sendKeys(" ");
    driver.findElement(By.cssSelector(".tn-elem__6254079351676828571748 > .tn-atom")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).sendKeys("(910) 159-80-90");
    driver.findElement(By.cssSelector("#form625407935 .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Andrey1990");
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("18");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("@");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Andrey T");
    driver.findElement(By.cssSelector("#form625407935 .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("0@mail.ru");
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("@mail.ru");
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys(" @mail.ru");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("a@mail.ru");
    driver.findElement(By.cssSelector("#form625407935 .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("@mail.ru");
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("andrei_telkov@mailru");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("andrei_telkov@.ru");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("andrei_telkov@mail.ru");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys(" Andrey T");
    driver.findElement(By.cssSelector("#form625407935 .t-checkbox__indicator")).click();
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Andrey T");
    driver.findElement(By.cssSelector(".js-error-control-box .t-checkbox__indicator")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).sendKeys("(910) 159-80");
    driver.findElement(By.cssSelector("#form625407935 .t-submit")).click();
    {
      WebElement element = driver.findElement(By.linkText("обработку персональных данных"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("tildaspec-phone-part[]")).click();
    driver.findElement(By.name("tildaspec-phone-part[]")).sendKeys("(910) 159-80-92");
  }
  @Test
  public void testsFooterselements() {
    driver.get("https://skillfactory.ru/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.xpath("//img[contains(@src,\'https://static.tildacdn.com/tild6235-3037-4336-a130-613832316539/7fe161b7-c965-41dd-9.svg\')]")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Отзывы студентов")).click();
    vars.put("win8976", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win8976").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("События и материалы")).click();
    vars.put("win4812", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4812").toString());
    js.executeScript("window.scrollTo(0,51.20000076293945)");
    js.executeScript("window.scrollTo(0,100)");
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Реферальная программа"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Реферальная программа")).click();
    vars.put("win5553", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win5553").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Акции"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Акции")).click();
    vars.put("win4057", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win4057").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Контакты")).click();
    vars.put("win8651", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8651").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Веб-разработка")).click();
    vars.put("win3912", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3912").toString());
    {
      WebElement element = driver.findElement(By.linkText("Frontend-разработка"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Backend-разработка")).click();
    vars.put("win3088", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3088").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-elem__6255251651676892134844 a:nth-child(7)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134844 a:nth-child(7)")).click();
    vars.put("win2311", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win2311").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Разработка приложений"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Разработка приложений")).click();
    vars.put("win974", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win974").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-atom > .t978__tm-link"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Безопасность")).click();
    vars.put("win7464", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7464").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Инфраструктура"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Инфраструктура")).click();
    vars.put("win3926", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win3926").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Разработка игр"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Разработка игр")).click();
    vars.put("win610", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win610").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("Создание сайтов")).click();
    {
      WebElement element = driver.findElement(By.linkText("Курсы Java"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Курсы Java")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-elem__5206504271652779744723 > .tn-atom"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Курсы Python"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Курсы Python")).click();
    {
      WebElement element = driver.findElement(By.linkText("Разработка приложений"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Курсы JavaScript")).click();
    {
      WebElement element = driver.findElement(By.linkText("Курсы PHP"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Курсы PHP")).click();
    vars.put("win7412", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win7412").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("Курсы IT")).click();
    driver.findElement(By.linkText("Курсы для старта")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 a:nth-child(19)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 .internal-link:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 .internal-link:nth-child(4)")).click();
    vars.put("win4072", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win4072").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 .internal-link:nth-child(7)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 .internal-link:nth-child(7)")).click();
    vars.put("win5397", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win5397").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Маркетинг")).click();
    vars.put("win8943", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8943").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 a:nth-child(13)")).click();
    vars.put("win1769", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1769").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134863 a:nth-child(19)")).click();
    vars.put("win5143", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5143").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("Корпоративное обучение")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".tn-elem__6255251651676892134844 a:nth-child(7)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Блогерам и бизнесу")).click();
    vars.put("win3720", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3720").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Сотрудничество"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Сотрудничество")).click();
    vars.put("win6120", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win6120").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Партнерская программа")).click();
    vars.put("win2891", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2891").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("Вакансии"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Вакансии")).click();
    vars.put("win9909", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win9909").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Центр карьеры")).click();
    vars.put("win7033", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7033").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Фэктори реальных проектов")).click();
    vars.put("win4874", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4874").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Skillfactory Media")).click();
    vars.put("win7383", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7383").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134944 .tn-atom__img")).click();
    vars.put("win457", waitForWindow(2000));
    driver.switchTo().window(vars.get("win457").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892134965 > .tn-atom")).click();
    vars.put("win8805", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8805").toString());
    driver.close();
    vars.put("window_handles", driver.getWindowHandles());
    driver.switchTo().window(vars.get("root").toString());
    vars.put("win8462", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8462").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892135006 > .tn-atom")).click();
    vars.put("win6922", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6922").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".tn-elem__6255251651676892135020 .tn-atom__img")).click();
    vars.put("win7257", waitForWindow(2000));
    driver.switchTo().window(vars.get("win7257").toString());
    driver.close();
    vars.put("window_handles", driver.getWindowHandles());
    driver.switchTo().window(vars.get("root").toString());
    vars.put("win6497", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6497").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
}
